FROM alpine:3.21.3

RUN apk update && \
    apk add --no-cache curl grep sed coreutils bash perl

VOLUME ["/data"]

COPY scraper.sh /scraper.sh
RUN chmod +x /scraper.sh
CMD ["/bin/bash", "/scraper.sh"]
